src/main/java/org/mamute/model/LoggedUser.java
package org.mamute.model;

import javax.servlet.http.HttpServletRequest;

import static com.google.common.base.Objects.firstNonNull;

public class LoggedUser {

	private final User user;
	private final HttpServletRequest request;

	public LoggedUser(User user, HttpServletRequest request) {
		this.user = user;
		this.request = request;
	}

	public User getCurrent() {
		return isLoggedIn() ? user : User.GHOST;
	}

	public String getIp() {
		if (request == null) {
			return null;
		}
		return firstNonNull(request.getHeader("X-Real-IP"), request.getRemoteAddr());
	}

	public boolean isModerator() {
		return isLoggedIn() ? user.isModerator() : false;
	}

	public boolean canModerate() {
		return isLoggedIn() ? user.canModerate() : false;
	}

	public boolean isLoggedIn() {
		return user != null;
	}

	@Override
	public String toString() {
		return "[user = " + user + ", ip = " + getIp() + "]";
	}


}

src/main/java/org/mamute/model/TagPage.java
package org.mamute.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;

import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

@Entity
public class TagPage {
	private static final int DESCRIPTION_MIN_LENGTH = 100;

	@Id
	@GeneratedValue
	private Long id;

	@ManyToOne
	private final Tag tag;

	@Lob
	@Length(min = DESCRIPTION_MIN_LENGTH, message = "tag_page.errors.about.length")
	@NotEmpty(message = "tag_page.errors.about.length")
	private String about;

	@Lob
	private String markedAbout;
	
	
	/**
	 * @deprecated hibernate eyes only
	 */
	TagPage() {
		this(null, MarkedText.notMarked(""));
	}
	
	public TagPage(Tag tag, MarkedText about) {
		this.tag = tag;
		setAbout(about);
	}
	
	public void setAbout(MarkedText about){
		this.about = about.getPure();
		this.markedAbout = about.getMarked();
	}

	public String getTagName() {
		return tag.getName();
	}
	
	public String getMarkedAbout() {
		return markedAbout;
	}
	
	public String getAbout() {
		return about;
	}

	public String getTagUriName() {
		return tag.getUriName();
	}
	
	public Tag getTag() {
		return tag;
	}
	
}

src/main/java/org/mamute/controllers/TagPageController.java
package org.mamute.controllers;

import javax.inject.Inject;

import org.mamute.brutauth.auth.rules.ModeratorOnlyRule;
import org.mamute.dao.TagDAO;
import org.mamute.dao.TagPageDAO;
import org.mamute.model.MarkedText;
import org.mamute.model.Tag;
import org.mamute.model.TagPage;
import org.mamute.validators.TagPageValidator;

import br.com.caelum.brutauth.auth.annotations.CustomBrutauthRules;
import br.com.caelum.vraptor.Controller;
import br.com.caelum.vraptor.Get;
import br.com.caelum.vraptor.Post;
import br.com.caelum.vraptor.Result;
import br.com.caelum.vraptor.routes.annotation.Routed;

@Routed
@Controller
public class TagPageController {

	@Inject private TagDAO tags;
	@Inject private Result result;
	@Inject private TagPageDAO tagPages;
	@Inject private TagPageValidator validator;

	@Get
	@CustomBrutauthRules(ModeratorOnlyRule.class)
	public void tagPageForm(String tagName){
		if(validator.validateCreationWithTag(tagName)){
			result.include("tag", tags.findByName(tagName));
		}
	}

	@Get
	@CustomBrutauthRules(ModeratorOnlyRule.class)
	public void editTagPageForm(String tagName){
		TagPage tagPage = tagPages.findByTag(tagName);
		result.include("tagPage", tagPage);
	}
	
	@Post
	@CustomBrutauthRules(ModeratorOnlyRule.class)
	public void editTagPage(String tagName, MarkedText about){
		TagPage tagPage = tagPages.findByTag(tagName);
		tagPage.setAbout(about);
		if(!validator.validate(tagPage)){
			validator.onErrorRedirectTo(TagPageController.class).editTagPageForm(tagPage.getTagName());
			return;
		}
		result.redirectTo(this).showTagPage(tagPage.getTagName());
	}
	
	@Post
	@CustomBrutauthRules(ModeratorOnlyRule.class)
	public void newTagPage(String tagName, MarkedText about){
		if(!validator.validateCreationWithTag(tagName)) return;
		Tag tag = tags.findByName(tagName);
		TagPage tagPage = new TagPage(tag, about);
		if(!validator.validate(tagPage)){
			validator.onErrorRedirectTo(TagPageController.class).tagPageForm(tagPage.getTagName());
			return;
		}
		tagPages.save(tagPage);
		result.redirectTo(this).showTagPage(tagPage.getTagName()); 
	}
	
	@Get
	public void showTagPage(String tagName){
		TagPage tagPage = tagPages.findByTag(tagName);
		result.include(tagPage);
		result.include("hasAbout", tags.hasAbout(tagPage.getTag()));
	}
}

src/main/webapp/WEB-INF/jsp/tagPage/editTagPageForm.jsp
<c:set var="title" value="${t['metas.tag_page.title']}"/>
<c:set var="siteName" value="${t['site.name']}"/>

<c:set var="genericTitle" value="${t['metas.generic.title'].args(siteName)}"/>

<tags:header title="${genericTitle} - ${title} - ${tag.name}"/>

<h2 class="title subheader page-title main-thread-title">${t['tag_page.form.edit.title']} ${tag.name}</h2>

<tags:tagPageForm uri="${linkTo[TagPageController].editTagPage(tag.name)}" submitTextKey="tag_page.form.edit.submit"/>

src/main/webapp/WEB-INF/jsp/tagPage/showTagPage.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<c:set var="siteName" value="${t['site.name']}"/>

<c:set var="description" value="${t['metas.default.description'].args(siteName)}"/>

<c:set var="genericTitle" value="${t['metas.generic.title'].args(siteName)}"/>

<tags:header facebookMetas="${true}" title="${genericTitle} - ${tagPage.tagName}" description="${description}"/>

<section class="first-content content">
	<tags:rssTagHeader tag="${tagPage.tag}"/>
	
	<tags:tagTabs tag="${tagPage.tag}" hasAbout="${hasAbout}"/>

	<div class="post-container about-tag">
		<div itemprop="articleBody" class="post-text">
			${tagPage.markedAbout}
		</div>
	</div>
	<c:if test="${currentUser.moderator}">
		<div class="post-interactions">
			<ul class="post-action-nav piped-nav nav">
				<li class="nav-item">
					<a class="post-action requires-login"
					    href="${linkTo[TagPageController].editTagPageForm(tagPage.tagUriName)}">
						${t['edit']}
					</a>
				</li>
			</ul>
		</div>
	</c:if>
</section>
<tags:sideBar recentTags="${recentQuestionTags}" relatedQuestions="${relatedQuestions}"/>

src/main/webapp/WEB-INF/jsp/tagPage/tagPageForm.jsp
<c:set var="title" value="${t['metas.tag_page.title']}"/>
<c:set var="siteName" value="${t['site.name']}"/>

<c:set var="genericTitle" value="${t['metas.generic.title'].args(siteName)}"/>

<tags:header title="${genericTitle} - ${title} - ${tag.name}"/>

<h2 class="title subheader page-title main-thread-title">${t['tag_page.form.new.title']} ${tag.name}</h2>
<tags:tagPageForm uri="${linkTo[TagPageController].newTagPage(tag.name)}" submitTextKey="tag_page.form.new.submit"/>