src/main/java/org/mamute/model/LoggedUser.java
package org.mamute.model;

import javax.servlet.http.HttpServletRequest;

import static com.google.common.base.Objects.firstNonNull;

public class LoggedUser {

	private final User user;
	private final HttpServletRequest request;

	public LoggedUser(User user, HttpServletRequest request) {
		this.user = user;
		this.request = request;
	}

	public User getCurrent() {
		return isLoggedIn() ? user : User.GHOST;
	}

	public String getIp() {
		if (request == null) {
			return null;
		}
		return firstNonNull(request.getHeader("X-Real-IP"), request.getRemoteAddr());
	}

	public boolean isModerator() {
		return isLoggedIn() ? user.isModerator() : false;
	}

	public boolean canModerate() {
		return isLoggedIn() ? user.canModerate() : false;
	}

	public boolean isLoggedIn() {
		return user != null;
	}

	@Override
	public String toString() {
		return "[user = " + user + ", ip = " + getIp() + "]";
	}


}

src/main/java/org/mamute/model/News.java
package org.mamute.model;

import static javax.persistence.FetchType.EAGER;
import static org.hibernate.annotations.CascadeType.SAVE_UPDATE;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.validation.constraints.NotNull;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.Type;
import org.joda.time.DateTime;
import org.mamute.infra.NotFoundException;
import org.mamute.model.interfaces.Moderatable;
import org.mamute.model.interfaces.RssContent;
import org.mamute.model.interfaces.ViewCountable;
import org.mamute.model.interfaces.Votable;
import org.mamute.model.interfaces.Watchable;
import org.mamute.model.watch.Watcher;
import org.mamute.providers.SessionFactoryCreator;
import org.owasp.html.HtmlPolicyBuilder;

@Entity
public class News extends Moderatable implements Post, ViewCountable, Watchable, RssContent, ReputationEventContext {
	@Id
	@GeneratedValue
	private Long id;

	@ManyToOne(optional = false, fetch = EAGER)
	@Cascade(SAVE_UPDATE)
	@NotNull
	private NewsInformation information = null;
	
	@OneToMany(mappedBy="news")
	@Cascade(SAVE_UPDATE)
	private List<NewsInformation> history = new ArrayList<>();
	
	@Type(type = SessionFactoryCreator.JODA_TIME_TYPE)
	private final DateTime createdAt = new DateTime();

	@Type(type = SessionFactoryCreator.JODA_TIME_TYPE)
	private DateTime lastUpdatedAt = new DateTime();

	@ManyToOne
	private User lastTouchedBy = null;

	@ManyToOne(fetch = EAGER)
	private final User author;

	private long views = 0l;
	
	@JoinTable(name = "News_Votes")
	@OneToMany
	private final List<Vote> votes = new ArrayList<>();

	private long voteCount = 0l;

	@Embedded
	private final NewsCommentList comments = new NewsCommentList();
	
	@Embedded
	private final ModerationOptions moderationOptions = new ModerationOptions();
	
	@JoinTable(name = "News_Flags")
	@OneToMany
	private final List<Flag> flags = new ArrayList<>();
	
	private boolean approved = false;
	
	@JoinTable(name = "News_Watchers")
	@OneToMany
	private final List<Watcher> watchers = new ArrayList<>();
	
	
	/**
	 * @deprecated hibernate eyes only
	 */
	public News() {
		author = null;
	}
	
	public News(NewsInformation newsInformation, User author) {
		this.author = author;
		enqueueChange(newsInformation, UpdateStatus.NO_NEED_TO_APPROVE);
	}

	@Override
	public void substitute(Vote previous, Vote current) {
		this.voteCount += current.substitute(previous, votes);
	}
	
	public void remove(Vote previous) {
		votes.remove(previous);
		this.voteCount -= previous.getCountValue();
//		addUserInteraction(vote.getAuthor());
	}

	@Override
	public User getAuthor() {
		return author;
	}

	@Override
	public Long getId() {
		return id;
	}

	@Override
	public long getVoteCount() {
		return voteCount;
	}

	@Override
	public Class<? extends Votable> getType() {
		return News.class;
	}

	@Override
	public Comment add(Comment comment) {
		comments.add(comment);
		return comment;
	}

	@Override
	public List<Comment> getVisibleCommentsFor(User user) {
		return comments.getVisibleCommentsFor(user);
	}

	@Override
	public DateTime getLastUpdatedAt() {
		return lastUpdatedAt;
	}

	@Override
	public User getLastTouchedBy() {
		return lastTouchedBy;
	}

	@Override
	public DateTime getCreatedAt() {
		return createdAt;
	}

	@Override
	public boolean isEdited() {
		return lastUpdatedAt.isAfter(createdAt);
	}

	@Override
	public boolean alreadyFlaggedBy(User user) {
		for (Flag flag : flags) {
			if (flag.createdBy(user))
				return true;
		}
		return false;
	}

	@Override
	public void remove() {
		moderationOptions.remove();
	}

	@Override
	public boolean isVisible() {
		return moderationOptions.isVisible();
	}

	@Override
	public boolean isVisibleForModeratorAndNotAuthor(User user) {
		return !this.isVisible() && user != null && !user.isAuthorOf(this);
	}
	
	@Override
	public String getTypeNameKey() {
		return "news.type_name";
	}

	@Override
	public NewsInformation getInformation() {
		return information;
	}

	@Override
	protected void updateApproved(Information approved) {
		NewsInformation approvedNews = (NewsInformation) approved;
		touchedBy(approvedNews.getAuthor());
		setInformation(approvedNews);		
	}

	private void setInformation(NewsInformation approvedNews) {
		approvedNews.setNews(this);
        this.information = approvedNews;		
	}

	private void touchedBy(User author) {
		this.lastTouchedBy = author;
		this.lastUpdatedAt = new DateTime();
	}

	@Override
	public String getTypeName() {
        return getType().getSimpleName();
    }
	
	@Override
	public boolean hasPendingEdits() {
		for (NewsInformation information : history) {
			if(information.isPending()) return true;
		}
		return false;
	}

	@Override
	public void add(Flag flag) {
		flags.add(flag);
	}

	@Override
	public Watchable getMainThread() {
		return this;
	}
	
	public String getTitle(){
		return information.getTitle();
	}

	public UpdateStatus updateWith(NewsInformation information) {
	    return new Updater().update(this, information);
	}

	public List<NewsInformation> getHistory() {
		return history;
	}

	@Override
	protected void addHistory(Information information) {
		this.history.add((NewsInformation) information);
	}

	public String getSluggedTitle() {
		return information.getSluggedTitle();
	}
	
	public String getMarkedDescription(){
		return information.getMarkedDescription();
	}
	
	public long getViews() {
		return views;
	}
	
	public News approved(){
		approved = true;
		return this;
	}
	
	public boolean isApproved(){
		return approved;
	}

	public boolean checkVisibilityFor(LoggedUser currentUser) {
		boolean isTheAuthor = currentUser.isLoggedIn() && currentUser.getCurrent().getId().equals(author.getId());
		if (isApproved() || currentUser.isModerator() || isTheAuthor) {
			return true;
		}
		throw new NotFoundException();
	}

	@Override
	public void ping() {
		views++;
	}

	@Override
	public Question getQuestion() {
		return null; //TODO dar um jeito
	}

	@Override
	public void add(Watcher watcher) {
		watchers.add(watcher);
	}

	@Override
	public void remove(Watcher watcher) {
		watchers.remove(watcher);
	}

	@Override
	public List<Watcher> getWatchers() {
		return watchers;
	}
	
	public String getDescription() {
		return getInformation().getDescription();
	}

	@Override
	public String getLinkPath() {
		return "noticias/" + id + "-" + getSluggedTitle();
	}
	
    public String getTrimmedContent() {
        String markedDescription = getMarkedDescription();
        if (markedDescription.length() < 125)
            return sanitize(markedDescription);
        return sanitize(markedDescription.substring(0, 125));
    }

	private String sanitize(String markedDescription) {
		return new HtmlPolicyBuilder().toFactory().sanitize(markedDescription) + "...";
	}

	@Override
	public List<Vote> getVotes() {
		return votes;
	}
}

src/main/java/org/mamute/controllers/ListController.java
package org.mamute.controllers;

import java.util.Arrays;
import java.util.List;

import javax.inject.Inject;
import javax.servlet.http.HttpServletResponse;

import org.joda.time.DateTime;
import org.mamute.components.RecentTagsContainer;
import org.mamute.dao.NewsDAO;
import org.mamute.dao.QuestionDAO;
import org.mamute.dao.TagDAO;
import org.mamute.model.LoggedUser;
import org.mamute.model.News;
import org.mamute.model.Question;
import org.mamute.model.Tag;
import org.mamute.stream.Streamed;

import br.com.caelum.vraptor.Controller;
import br.com.caelum.vraptor.Get;
import br.com.caelum.vraptor.Result;
import br.com.caelum.vraptor.actioncache.Cached;
import br.com.caelum.vraptor.routes.annotation.Routed;

@Routed
@Controller
public class ListController {

	@Inject private LoggedUser loggedUser;
	@Inject private QuestionDAO questions;
	@Inject private Result result;
	@Inject private TagDAO tags;
	@Inject private RecentTagsContainer recentTagsContainer;
	@Inject private NewsDAO newses;
	@Inject private RecentTagsContainer tagsContainer;
	@Inject private HttpServletResponse response;
	
	@Get
	public void home(Integer p) {
		Integer page = getPage(p);
		List<Question> visible = questions.allVisible(page);
		if (visible.isEmpty() && page != 1) {
			result.notFound();
			return;
		}
		List<String> tabs = Arrays.asList("voted", "answered", "viewed");
		result.include("tabs", tabs);

		result.include("questions", visible);
		result.include("totalPages", questions.numberOfPages());
		result.include("currentPage", page);
		result.include("currentUser", loggedUser);
	}

	@Streamed
	public void streamedHome(Integer p) {
		List<String> tabs = Arrays.asList("voted", "answered", "viewed");
		result.include("tabs", tabs);
		result.include("currentUser", loggedUser);
	}

	@Cached(key="questionListPagelet", duration = 30, idleTime = 30)
	@Streamed
	public void questionListPagelet(Integer p) {
		List<String> tabs = Arrays.asList("voted", "answered", "viewed");
		result.include("tabs", tabs);
		result.include("currentUser", loggedUser);
		Integer page = getPage(p);
		List<Question> visible = questions.allVisible(page);
		if (visible.isEmpty() && page != 1) {
			result.notFound();
			return;
		}

		result.include("questions", visible);
		result.include("totalPages", questions.numberOfPages());
		result.include("currentPage", page);
		result.forwardTo("/WEB-INF/jsp/list/questionListPagelet.jspf");
		System.out.println("executing questionListPagelet");
	}

	@Cached(key="sideBarPagelet", duration = 30, idleTime = 30)
	@Streamed
	public void sideBarPagelet() {
		result.include("sidebarNews", newses.allVisibleAndApproved(5));
		result.include("recentTags", tagsContainer.getRecentTagsUsage());
		result.forwardTo("/WEB-INF/jsp/list/sideBarPagelet.jspf");

	}

	@Get
	public void topRaw() {
		result.redirectTo(this).top("voted");
	}

	@Get
	public void top(String section) {
		Integer count = 35;
		
		List<String> tabs = Arrays.asList("voted", "answered", "viewed");
		if (!tabs.contains(section)) {
			section = tabs.get(0);
			result.redirectTo(this).top(section);
			return;
		}

		DateTime since = DateTime.now().minusMonths(2);
		List<Question> top = questions.top(section, count, since);
		
		if (top.isEmpty()) {
			result.notFound();
			return;
		}
		result.include("tabs", tabs);
		result.include("section", section);
		result.include("questions", top);
		result.include("currentUser", loggedUser);
	}
	
	@Get
	public void hackedIndex() {
		result.redirectTo(this).home(1);
	}

	@Get
	public void news(Integer p) {
		Integer page = getPage(p);
		List<News> visible = newses.allVisible(page, 25);
		if (visible.isEmpty() && page != 1) {
			result.notFound();
			return;
		}
		result.include("newses", visible);
		result.include("totalPages", newses.numberOfPages(25));
		result.include("currentPage", page);
		result.include("newsActive", true);
		result.include("noDefaultActive", true);
	}
	
	@Get
	public void unsolved(Integer p) {
		Integer page = getPage(p);
		result.include("questions", questions.unsolvedVisible(page));
		result.include("recentTags", recentTagsContainer.getRecentTagsUsage());
		result.include("currentPage", page);
		result.include("totalPages", questions.totalPagesUnsolvedVisible());
	}
	
	@Get
	public void unanswered(Integer p) {
		Integer page = getPage(p);
		result.include("questions", questions.unanswered(page));
		result.include("recentTags", recentTagsContainer.getRecentTagsUsage());
		result.include("currentPage", page);
		result.include("totalPages", questions.totalPagesWithoutAnswers());
		result.include("unansweredActive", true);
		result.include("noDefaultActive", true);
	}
	
	@Get
	public void withTag(String tagName, Integer p, boolean semRespostas) {
		Integer page = getPage(p);
		Tag tag = tags.findByName(tagName);
		if(tag == null){
			result.notFound();
			return;
		}
		List<Question> questionsWithTag = questions.withTagVisible(tag, page, semRespostas);
		result.include("totalPages", questions.numberOfPages(tag));
		result.include("tag", tag);
		result.include("recentTags", recentTagsContainer.getRecentTagsUsage());
		result.include("questions", questionsWithTag);
		result.include("currentPage", page);
		result.include("hasAbout", tags.hasAbout(tag));
		if (semRespostas) {
			result.include("unansweredActive", true);
			result.include("noDefaultActive", true);
			result.include("unansweredTagLinks", true);
		}
	}
	
	@Get
	public void listTags(){
		result.include("tags", tags.all());
	}
	
	private Integer getPage(Integer p) {
		Integer page = p == null ? 1 : p;
		return page;
	}

}

src/main/java/org/mamute/controllers/NewsController.java
package org.mamute.controllers;

import javax.inject.Inject;

import org.mamute.brutauth.auth.rules.EditNewsRule;
import org.mamute.brutauth.auth.rules.InputRule;
import org.mamute.brutauth.auth.rules.LoggedRule;
import org.mamute.brutauth.auth.rules.ModeratorOnlyRule;
import org.mamute.dao.NewsDAO;
import org.mamute.dao.VoteDAO;
import org.mamute.dao.WatcherDAO;
import org.mamute.model.Information;
import org.mamute.model.LoggedUser;
import org.mamute.model.MarkedText;
import org.mamute.model.News;
import org.mamute.model.NewsInformation;
import org.mamute.model.UpdateStatus;
import org.mamute.model.User;
import org.mamute.model.post.PostViewCounter;

import br.com.caelum.brutauth.auth.annotations.CustomBrutauthRules;
import br.com.caelum.vraptor.Controller;
import br.com.caelum.vraptor.Get;
import br.com.caelum.vraptor.Post;
import br.com.caelum.vraptor.Result;
import br.com.caelum.vraptor.hibernate.extra.Load;
import br.com.caelum.vraptor.routes.annotation.Routed;

@Routed
@Controller
public class NewsController {

	@Inject private LoggedUser currentUser;
	@Inject private NewsDAO newses;
	@Inject private Result result;
	@Inject private VoteDAO votes;
	@Inject private PostViewCounter viewCounter;
	@Inject private WatcherDAO watchers;

	@Post
	@CustomBrutauthRules({LoggedRule.class, InputRule.class})
	public void newNews(String title, MarkedText description) {
		NewsInformation information = new NewsInformation(title, description, currentUser, "new news");
		User author = currentUser.getCurrent();
		News news = new News(information, author);
		result.include("news", news);
		newses.save(news);
		result.redirectTo(this).showNews(news, news.getSluggedTitle());
	}
	
	@Get
	@CustomBrutauthRules({LoggedRule.class, InputRule.class})
	public void newsForm() {
		result.include("newsActive", true);
		result.include("noDefaultActive", true);
	}
	
	@Get
	@CustomBrutauthRules(EditNewsRule.class)
	public void newsEditForm(@Load News news) {
		result.include("news", news);
		result.include("newsActive", true);
		result.include("noDefaultActive", true);
	}
	
	@Post
	@CustomBrutauthRules(EditNewsRule.class)
	public void saveEdit(@Load News news, String title, MarkedText description, String comment) {
		Information newInformation = new NewsInformation(title, description, currentUser, comment);
		news.enqueueChange(newInformation, UpdateStatus.NO_NEED_TO_APPROVE);
		result.redirectTo(this).showNews(news, news.getSluggedTitle());
	}
	
	@Get
	public void showNews(@Load News news, String sluggedTitle) {
		User current = currentUser.getCurrent();
		news.checkVisibilityFor(currentUser);
		redirectToRightUrl(news, sluggedTitle);
		viewCounter.ping(news);
		boolean isWatching = watchers.ping(news, current);
		
		result.include("commentsWithVotes", votes.previousVotesForComments(news, current));
		result.include("currentVote", votes.previousVoteFor(news.getId(), current, News.class));
		result.include("news", news);
		result.include("isWatching", isWatching);
		result.include("userMediumPhoto", true);
		result.include("newsActive", true);
		result.include("noDefaultActive", true);
	}
	
	@Post
	@CustomBrutauthRules(ModeratorOnlyRule.class)
	public void approve(@Load News news){
		news.approved();
		result.nothing();
	}

	private void redirectToRightUrl(News news, String sluggedTitle) {
		if (!news.getSluggedTitle().equals(sluggedTitle)) {
			result.redirectTo(this).showNews(news, news.getSluggedTitle());
			return;
		}
	}
}

src/main/webapp/WEB-INF/jsp/list/home.jsp
<c:set var="siteName" value="${t['site.name']}"/>
<c:set var="title" value="${t['metas.home.title']}"/>
<c:set var="description" value="${t['metas.default.description'].args(siteName)}"/>
<c:set var="genericTitle" value="${t['metas.generic.title'].args(siteName)}"/>

<tags:header facebookMetas="${true}" title="${genericTitle} - ${title}" description="${description}"/>

<c:set var="title" value="${t['menu.questions']}"/>

<c:if test="${!currentUser.loggedIn}">
	<section class="about-banner">
		<span class="minimize-banner icon-minus"></span>
		<div class="about-content tell-me-more">
			<h3 class="about-title title">
				${t['about.home_banner.welcome'].args(siteName)}
			</h3>
			<div class="about-text">
				${t['about.home_banner.text'].args(siteName)}
			</div>
			<a href="${linkTo[NavigationController].about}">
				${t['about.home_banner.text.link'].args(siteName)}
			</a>
		</div>
		<div class="about-content how-it-works">
			<ul>
				<tags:howItWorksItem icon="icon-comment" key="about.home_banner.how_it_works.anyone_ask"/>
				<tags:howItWorksItem icon="icon-chat-empty" key="about.home_banner.how_it_works.anyone_answer"/>
				<tags:howItWorksItem icon="icon-users" key="about.home_banner.how_it_works.answers_raise_up"/>
			</ul> 
		</div>
	</section>
</c:if>


<section class="first-content content">
	<tags:questionList recentTags="${recentTags}" questions="${questions}" title="${title}" tabs="${tabs}"/>
</section>
<tags:joyrideIntro />

<tags:sideBar recentTags="${recentTags}" />

src/main/webapp/WEB-INF/jsp/list/listTags.jsp
<c:set var="title" value="${t['metas.tags.title']}"/>
<c:set var="siteName" value="${t['site.name']}"/>

<c:set var="genericTitle" value="${t['metas.generic.title'].args(siteName)}"/>

<tags:header title="${genericTitle} - ${title}"/>

<h2 class="title page-title subheader">${t['menu.tags']}</h2>
<ol class="tags-list complete-tags">
	<c:forEach var="tag" items="${tags}">
		<li class="complete-tag">
			<tags:tag tag="${tag}"/> x ${tag.usageCount}
			<div class='tag-description'>${tag.description}</div>
		</li>
	</c:forEach>
</ol>

src/main/webapp/WEB-INF/jsp/list/news.jsp
<c:set var="siteName" value="${t['site.name']}"/>

<c:set var="description" value="${t['metas.default.description'].args(siteName)}"/>

<c:set var="genericTitle" value="${t['metas.generic.title'].args(siteName)}"/>

<tags:header facebookMetas="${true}" title="${genericTitle} - ${title}" description="${description}"/>

<section class="news-content content">
	<div class="subheader news-aside-list-header">
		<h2 class="title page-title">${t['menu.news']}	</h2>	
		<a href="${linkTo[RssController].newsRss}" class="rss-link"><i class="icon-rss "></i></a>
		<a href="${linkTo[NewsController].newsForm}" class="send-news">
			${t['menu.new_news']}
		</a>				
	</div>
	<c:if test="${not empty newses}">
		<ol class="news-list">
			<c:forEach var="news" items="${newses}">
				<tags:newsListItem news="${news}"/>
			</c:forEach>
		</ol>
	</c:if>
	<c:if test="${empty newses}">
		<h2 class="title section-title">${t['newses.empty_list']}</h2>
	</c:if>
	<tags:pagination url="${currentUrl}" currentPage="${currentPage}" totalPages="${totalPages}" delta="2"/>
</section>

src/main/webapp/WEB-INF/jsp/list/streamedHome.jsp
<%@taglib prefix="streamer" uri="http://vraptor.org/jsp/taglib/streamer" %>

<c:set var="siteName" value="${t['site.name']}"/>

<c:set var="title" value="${t['metas.home.title']}"/>

<c:set var="description" value="${t['metas.default.description'].args(siteName)}"/>

<c:set var="genericTitle" value="${t['metas.generic.title'].args(siteName)}"/>

<tags:header facebookMetas="${true}" title="${genericTitle} - ${title}" description="${description}"/>

<c:set var="title" value="${t['menu.questions']}"/>

<c:if test="${!currentUser.loggedIn}">
	<section class="about-banner">
		<span class="minimize-banner icon-minus"></span>
		<div class="about-content tell-me-more">
			<h3 class="about-title title">
				${t['about.home_banner.welcome'].args(siteName)}
			</h3>
			<div class="about-text">
				${t['about.home_banner.text'].args(siteName)}
			</div>
			<a href="${linkTo[NavigationController].about}">
				${t['about.home_banner.text.link'].args(siteName)}
			</a>
		</div>
		<div class="about-content how-it-works">
			<ul>
				<tags:howItWorksItem icon="icon-comment" key="about.home_banner.how_it_works.anyone_ask"/>
				<tags:howItWorksItem icon="icon-chat-empty" key="about.home_banner.how_it_works.anyone_answer"/>
				<tags:howItWorksItem icon="icon-users" key="about.home_banner.how_it_works.answers_raise_up"/>
			</ul> 
		</div>
	</section>
</c:if>


<div id="question-list-container"></div>
<div id="side-bar-container"></div>
<streamer:stream>
    <streamer:page url="questionListPagelet"/>
    <streamer:page url="sideBarPagelet"/>
</streamer:stream>

<tags:joyrideIntro />

src/main/webapp/WEB-INF/jsp/list/top.jsp
<c:set var="siteName" value="${t['site.name']}"/>

<c:set var="title" value="${t['metas.home.title']}"/>

<c:set var="description" value="${t['metas.default.description'].args(siteName)}"/>

<c:set var="genericTitle" value="${t['metas.generic.title'].args(siteName)}"/>

<tags:header facebookMetas="${true}" title="${genericTitle} - ${title}" description="${description}"/>

<%-- <tags:tabs titleKey="menu.top">
	<a href="${linkTo[ListController].top('voted')}">${t['menu.top.voted']}</a>
	<a href="${linkTo[ListController].top('answered')}">${t['menu.top.answered']}</a>
</tags:tabs> --%>
<c:set var="title" value="${t['menu.questions']}"/>

<section class="first-content content">
	<tags:questionList recentTags="${recentTags}" 
		questions="${questions}" title="${title}" tabs="${tabs}"/>
</section>

<tags:sideBar recentTags="${recentTags}" />

<tags:joyrideIntro />

src/main/webapp/WEB-INF/jsp/list/unanswered.jsp
<c:set var="siteName" value="${t['site.name']}"/>

<c:set var="title" value="${t['metas.unanswered.title']}"/>

<c:set var="description" value="${t['metas.default.description'].args(siteName)}"/>

<c:set var="genericTitle" value="${t['metas.generic.title'].args(siteName)}"/>

<tags:header facebookMetas="${true}" title="${genericTitle} - ${title}" description="${description}"/>

<c:set var="title" value="${t['menu.unanswered']}"/>
<section class="first-content content">
	<tags:questionList recentTags="${recentTags}" 
			questions="${questions}" title="${title}" unansweredTagLinks="${true}"/>
</section>
<tags:sideBar recentTags="${recentTags}" />
<tags:joyrideIntro />

src/main/webapp/WEB-INF/jsp/list/unsolved.jsp
<c:set var="siteName" value="${t['site.name']}"/>

<c:set var="title" value="${t['metas.unsolved.title']}"/>

<c:set var="description" value="${t['metas.default.description'].args(siteName)}"/>

<c:set var="genericTitle" value="${t['metas.generic.title'].args(siteName)}"/>

<tags:header facebookMetas="${true}" title="${genericTitle} - ${title}" description="${description}"/>

<c:set var="title" value="${t['menu.unsolved']}"/>
<section class="first-content content">
	<tags:questionList recentTags="${recentTags}" questions="${questions}" title="${title}"/>
</section>
<tags:sideBar recentTags="${recentTags}" />
<tags:joyrideIntro />

src/main/webapp/WEB-INF/jsp/list/withTag.jsp
<c:set var="siteName" value="${t['site.name']}"/>

<c:set var="title" value="${t['metas.home.title']}"/>

<c:set var="description" value="${t['metas.default.description'].args(siteName)}"/>

<c:set var="genericTitle" value="${t['metas.generic.title'].args(siteName)}"/>

<tags:header facebookMetas="${true}" title="${genericTitle} - ${title}" description="${description}"/>

<c:set var="title" value="${t['tag_list.title']}"/>
<section class="first-content content">
	<tags:questionList recentTags="${recentTags}" 
		questions="${questions}" title="${}" unansweredTagLinks="${unansweredTagLinks}"/>
</section>
<tags:sideBar recentTags="${recentTags}" />
<tags:joyrideIntro />