src/main/java/org/mamute/model/User.java
package org.mamute.model;

import static org.mamute.infra.Digester.hashFor;
import static org.mamute.infra.NormalizerBrutal.toSlug;
import static org.mamute.model.SanitizedText.fromTrustedText;
import static org.mamute.validators.UserPersonalInfoValidator.ABOUT_LENGTH_MESSAGE;
import static org.mamute.validators.UserPersonalInfoValidator.ABOUT_MAX_LENGTH;
import static org.mamute.validators.UserPersonalInfoValidator.ABOUT_MIN_LENGTH;
import static org.mamute.validators.UserPersonalInfoValidator.EMAIL_LENGTH_MESSAGE;
import static org.mamute.validators.UserPersonalInfoValidator.EMAIL_MAX_LENGTH;
import static org.mamute.validators.UserPersonalInfoValidator.EMAIL_MIN_LENGTH;
import static org.mamute.validators.UserPersonalInfoValidator.EMAIL_NOT_VALID;
import static org.mamute.validators.UserPersonalInfoValidator.LOCATION_LENGTH_MESSAGE;
import static org.mamute.validators.UserPersonalInfoValidator.LOCATION_MAX_LENGTH;
import static org.mamute.validators.UserPersonalInfoValidator.MARKED_ABOUT_MAX_LENGTH;
import static org.mamute.validators.UserPersonalInfoValidator.NAME_LENGTH_MESSAGE;
import static org.mamute.validators.UserPersonalInfoValidator.NAME_MAX_LENGTH;
import static org.mamute.validators.UserPersonalInfoValidator.NAME_MIN_LENGTH;
import static org.mamute.validators.UserPersonalInfoValidator.NAME_REQUIRED;
import static org.mamute.validators.UserPersonalInfoValidator.WEBSITE_LENGTH_MESSAGE;
import static org.mamute.validators.UserPersonalInfoValidator.WEBSITE_MAX_LENGHT;
import static org.mamute.validators.UserPersonalInfoValidator.WEBSITE_MIN_LENGTH;

import java.io.UnsupportedEncodingException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;

import javax.enterprise.inject.Vetoed;
import javax.persistence.Cacheable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.Type;
import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;
import org.joda.time.DateTime;
import org.joda.time.Years;
import org.mamute.auth.rules.PermissionRulesConstants;
import org.mamute.dto.UserPersonalInfo;
import org.mamute.infra.Digester;
import org.mamute.model.interfaces.Identifiable;
import org.mamute.model.interfaces.Moderatable;
import org.mamute.model.interfaces.Votable;
import org.mamute.model.watch.Watcher;
import org.mamute.providers.SessionFactoryCreator;

@Cacheable
@Cache(usage=CacheConcurrencyStrategy.READ_WRITE, region="cache")
@Table(name="Users")
@Entity
@Vetoed
public class User implements Identifiable {
	
	@Type(type = SessionFactoryCreator.JODA_TIME_TYPE)
	private final DateTime createdAt = new DateTime();
	
	@Id
	@GeneratedValue
	private Long id;

	@NotEmpty(message = NAME_REQUIRED)
	@Length(min = NAME_MIN_LENGTH, max = NAME_MAX_LENGTH, message = NAME_LENGTH_MESSAGE)
	private String name;
	
	@Length(min = WEBSITE_MIN_LENGTH, max = WEBSITE_MAX_LENGHT, message = WEBSITE_LENGTH_MESSAGE)
	private String website;
	
	@Length(max = LOCATION_MAX_LENGTH, message = LOCATION_LENGTH_MESSAGE)
	private String location;
	
	private String about;
	
	private String markedAbout;
	
	@Type(type = SessionFactoryCreator.JODA_TIME_TYPE)
	private DateTime birthDate;
	
	private long karma = 0;
	
	private boolean moderator = false;

	private boolean confirmedEmail = false;

	private String forgotPasswordToken = "";
	
	private String photoUri;
	
	@Type(type = "text")
	@NotEmpty
	private String sluggedName;
	
	@Type(type = SessionFactoryCreator.JODA_TIME_TYPE)
	private DateTime nameLastTouchedAt;

	@OneToMany(mappedBy="user")
	private final List<LoginMethod> loginMethods = new ArrayList<>();

	public static final User GHOST;

	@Length(min = EMAIL_MIN_LENGTH, max = EMAIL_MAX_LENGTH, message = EMAIL_LENGTH_MESSAGE)
	@Email(message = EMAIL_NOT_VALID)
	private String email;

	private boolean isSubscribed = true;
	
	private boolean isBanned = false;
	
	@OneToMany(mappedBy = "watcher")
	private final List<Watcher> watches = new ArrayList<>();
	
	@Type(type = SessionFactoryCreator.JODA_TIME_TYPE)
	private DateTime lastUpvote = new DateTime();
	
	
	static {
		GHOST = new User(fromTrustedText("GHOST"), "");
		GHOST.setId(1000l);
	}
	
	/**
	 * @deprecated hibernate eyes only
	 */
	protected User() {
		this(fromTrustedText(""), "");
	}

	public User(SanitizedText name, String email) {
		setName(name);
		this.email = email;
	}

	public DateTime getNameLastTouchedAt() {
		return nameLastTouchedAt;
	}

	public UserSession newSession() {
	    Long currentTimeMillis = System.currentTimeMillis();
	    String sessionKey = Digester.encrypt(currentTimeMillis.toString() + this.id.toString());
	    UserSession userSession = new UserSession(this, sessionKey);
	    return userSession;
    }

    public void setName(SanitizedText name) {
		this.name = name.getText();
		this.sluggedName = toSlug(this.name);
		this.nameLastTouchedAt = new DateTime();
	}

    public void setId(Long id) {
    	this.id = id;
    }
	
	public void setPhotoUri(URL storedUri) {
		photoUri = storedUri.toString();
	}
	
	public void setPersonalInformation(UserPersonalInfo info) {
		this.birthDate = info.getBirthDate();
		this.name = info.getName();
		this.email = info.getEmail();
		this.website = info.getWebsite();
		this.location = info.getLocation();
		this.about = info.getAbout();
		this.markedAbout = info.getMarkedAbout();
		this.isSubscribed = info.isSubscribed();
	}

	void setKarma(long karma) {
        this.karma = karma;
    }

	public boolean isSubscribedToNewsletter() {
		return isSubscribed;
	}
	
	public Long getId() {
		return this.id;
	}
	
	public String getSmallPhoto(String gravatarUrl) {
	    return getPhoto(32, 32, gravatarUrl);
	}
	
	public String getMediumPhoto(String gravatarUrl) {
		return getPhoto(48, 48, gravatarUrl);
	}
	
	public String getBigPhoto(String gravatarUrl) {
		return getPhoto(128, 128, gravatarUrl);
	}

	public String getName() {
		return name;
	}

	public long getKarma() {
		return karma;
	}

	public String getEmail() {
		return email;
	}

	public String getSluggedName() {
		return sluggedName;
	}
	
	public DateTime getCreatedAt() {
		return createdAt;
	}
	
	public String getWebsite() {
		return website;
	}
	
	public String getLocation() {
		return location;
	}
	
	public DateTime getBirthDate() {
		return birthDate;
	}
	
	public Integer getAge() {
		DateTime now = new DateTime();
		if (birthDate == null){
			return null;
		}
		return Years.yearsBetween(birthDate, now).getYears();
	}
	
	public LoginMethod getBrutalLogin() {
		for (LoginMethod method : loginMethods) {
			if (method.isBrutal()) {
				return method;
			}
		}
		throw new IllegalStateException("this guy dont have a brutal login method!");
	}
	
	public String getPhoto(Integer width, Integer height, String gravatarUrl) {
		String size = width + "x" + height;
		if (photoUri == null) {
			String digest = Digester.md5(email);
			String robohash = "http://robohash.org/size_"+size+"/set_set1/bgset_any/"+digest+".png";
			String gravatar = gravatarUrl + "/avatar/" + digest + ".png?r=PG&size=" + size;
			try {
				return gravatar + "&d=" + java.net.URLEncoder.encode(robohash, "UTF-8");
			} catch (UnsupportedEncodingException e) {
				return gravatar;
			}
		} else if (photoUri.contains("googleusercontent")) {
            return photoUri.replaceAll("sz=(\\d+)", "sz="+width);
        } else {
			return photoUri + "?width=" + width + "&height=" + height;
		}
	}
	
	public String getAbout() {
		return about;
	}
	
	public String getMarkedAbout() {
		return markedAbout;
	}

	@Override
	public String toString() {
		return "[User " + email + ", "+ name +", "+ id +"]";
	}
	
	public boolean isModerator() {
		return moderator;
	}

	public User asModerator() {
		this.moderator = true;
		return this;
	}

	public User removeModerator() {
		this.moderator = false;
		return this;
	}
	
	public boolean canModerate() {
		return isModerator() || this.karma >= PermissionRulesConstants.MODERATE_EDITS;
	}
	
	public void setSubscribed(boolean isSubscribed){
		this.isSubscribed = isSubscribed;
	}

	public String touchForgotPasswordToken() {
		String tokenSource = Math.random() + System.currentTimeMillis() + getEmail() + getId();
		this.forgotPasswordToken = Digester.encrypt(tokenSource);
		return forgotPasswordToken;
	}

	public boolean isValidForgotPasswordToken(String token) {
		return this.forgotPasswordToken.equals(token);
	}

	public boolean updateForgottenPassword(String password,
			String passwordConfirmation) {
		if (!password.equals(passwordConfirmation)) {
			return false;
		}
		for (LoginMethod method : loginMethods) {
			method.updateForgottenPassword(password);
		}
		return true;
	}

	public UpdateStatus approve(Moderatable moderatable, Information approvedInfo) {
	    if (this.canModerate()) {
	        moderatable.approve(approvedInfo);
	        approvedInfo.moderate(this, UpdateStatus.APPROVED);
	    }
        return UpdateStatus.REFUSED;
	}

	public void descreaseKarma(int value) {
        this.karma -= value;
    }

    public void increaseKarma(int value) {
        this.karma += value;
    }
    
    public void confirmEmail(){
    	confirmedEmail = true;
	}
    
	public void add(LoginMethod brutalLogin) {
		loginMethods.add(brutalLogin);
	}

	public boolean isAuthorOf(Votable votable) {
		return id == votable.getAuthor().getId();
	}
	
	public boolean hasKarmaToAnswerOwnQuestion() {
		return (this.karma >= PermissionRulesConstants.ANSWER_OWN_QUESTION) || isModerator(); 
	}
	
	public boolean hasKarmaToAnswerInactiveQuestion() {
		return (this.karma >= PermissionRulesConstants.INACTIVE_QUESTION) || isModerator(); 
	}
	
	public List<LoginMethod> getLoginMethods() {
		return loginMethods;
	}

	@Override
	public int hashCode() {

src/main/java/org/mamute/controllers/UserProfileController.java
package org.mamute.controllers;

import static java.util.Arrays.asList;
import static org.mamute.dao.WithUserPaginatedDAO.OrderType.ByDate;
import static org.mamute.dao.WithUserPaginatedDAO.OrderType.ByVotes;
import static org.mamute.model.SanitizedText.fromTrustedText;

import javax.inject.Inject;

import org.joda.time.DateTime;
import org.mamute.brutauth.auth.rules.ModeratorOnlyRule;
import org.mamute.dao.AnswerDAO;
import org.mamute.dao.FlaggableDAO;
import org.mamute.dao.PaginatableDAO;
import org.mamute.dao.QuestionDAO;
import org.mamute.dao.ReputationEventDAO;
import org.mamute.dao.TagDAO;
import org.mamute.dao.UserDAO;
import org.mamute.dao.WatcherDAO;
import org.mamute.dao.WithUserPaginatedDAO.OrderType;
import org.mamute.dto.UserPersonalInfo;
import org.mamute.factory.MessageFactory;
import org.mamute.model.LoggedUser;
import org.mamute.model.MarkedText;
import org.mamute.model.SanitizedText;
import org.mamute.model.User;
import org.mamute.validators.UserPersonalInfoValidator;

import br.com.caelum.brutauth.auth.annotations.CustomBrutauthRules;
import br.com.caelum.vraptor.Controller;
import br.com.caelum.vraptor.Get;
import br.com.caelum.vraptor.Path;
import br.com.caelum.vraptor.Post;
import br.com.caelum.vraptor.Result;
import br.com.caelum.vraptor.hibernate.extra.Load;
import br.com.caelum.vraptor.routes.annotation.Routed;

@Routed
@Controller
public class UserProfileController extends BaseController{
	
	private static final String HTTP = "http://";
	@Inject private Result result;
	@Inject private UserDAO users;
	@Inject private LoggedUser currentUser;
	@Inject private UserPersonalInfoValidator infoValidator;
	@Inject private QuestionDAO questions;
	@Inject private AnswerDAO answers;
    @Inject private TagDAO tags;
	@Inject private WatcherDAO watchers;
	@Inject private ReputationEventDAO reputationEvents;
	@Inject private MessageFactory messageFactory;
	@Inject private FlaggableDAO flaggable;

	@Get
	public void showProfile(@Load User user, String sluggedName){
		if (redirectToRightSluggedName(user, sluggedName)) {
			return;
		}
		
		result.include("isCurrentUser", currentUser.getCurrent().getId().equals(user.getId()));
		result.include("questionsByVotes", questions.ofUserPaginatedBy(user, ByVotes, 1));
		result.include("questionsCount", questions.countWithAuthor(user));
		result.include("answersByVotes", answers.ofUserPaginatedBy(user, ByVotes, 1));
		result.include("answersCount", answers.countWithAuthor(user));
		result.include("watchedQuestions", watchers.ofUserPaginatedBy(user, ByDate, 1));
		result.include("watchedQuestionsCount", watchers.countWithAuthor(user));
		
		result.include("reputationHistory", reputationEvents.karmaWonByQuestion(user, new DateTime().minusMonths(1), 5).getHistory());
		
		result.include("questionsPageTotal", questions.numberOfPagesTo(user));
		result.include("answersPageTotal", answers.numberOfPagesTo(user));
		result.include("watchedQuestionsPageTotal", watchers.numberOfPagesTo(user));
		
		result.include("userProfileMainTags", tags.findMainTagsOfUser(user));
		result.include("selectedUser", user);
		result.include("usersActive", true);
		result.include("noDefaultActive", true);
	}
	
	@Get
	@Path(priority=Path.HIGH, value="")
	public void reputationHistory(@Load User user, String sluggedName) {
		if (redirectToRightSluggedName(user, sluggedName)) {
			return;
		}
		result.include("selectedUser", user);
		result.include("reputationHistory", reputationEvents.karmaWonByQuestion(user).getHistory());
		result.include("usersActive", true);
		result.include("noDefaultActive", true);
	}

	@Get
	public void typeByVotesWith(Long id, String sluggedName, OrderType order, Integer p, String type){
		User author = users.findById(id);
		order = order == null ? ByVotes : order;
		Integer page = p == null ? 1 : p;
		PaginatableDAO paginatableDAO = type.equals("perguntas") ? questions : answers;
		result.forwardTo(BrutalTemplatesController.class).userProfilePagination(paginatableDAO, author, order, page, type);		
	}
	
	@Get
	public void watchersByDateWith(Long id, String sluggedName, Integer p){
		User user = users.findById(id);
		Integer page = p == null ? 1 : p;
		result.forwardTo(BrutalTemplatesController.class).userProfilePagination(watchers, user, ByDate, page, "acompanhadas");
	}
		
	@Get
	public void editProfile(@Load User user){
		if (!user.getId().equals(currentUser.getCurrent().getId())){
			result.redirectTo(ListController.class).home(null);
			return;
		}
		result.include("user", user);
		result.include("usersActive", true);
		result.include("noDefaultActive", true);
	}
	
	@Post
	public void editProfile(@Load User user, SanitizedText name, String email, 
			SanitizedText website, SanitizedText location, DateTime birthDate, MarkedText description, boolean isSubscribed) {
		if (!user.getId().equals(currentUser.getCurrent().getId())){
			result.redirectTo(ListController.class).home(null);
			return;
		}
		
		if (website != null) {
			website = correctWebsite(website);
		}

		UserPersonalInfo info = new UserPersonalInfo(user)
			.withName(name)
			.withEmail(email)
			.withWebsite(website)
			.withLocation(location)
			.withBirthDate(birthDate)
			.withAbout(description)
			.withIsSubscribed(isSubscribed);
		
		if (!infoValidator.validate(info)) {
			infoValidator.onErrorRedirectTo(this).editProfile(user);
			return;
		}
		
		users.updateLoginMethod(user, email);
		
		user.setPersonalInformation(info);
		
		result.redirectTo(this).showProfile(user, user.getSluggedName());
	}
	
	@Get
	public void unsubscribe(@Load User user, String hash){
		String correctHash = user.getUnsubscribeHash();
		
		if (!correctHash.equals(hash)) {
			result.include("mamuteMessages", asList(messageFactory.build("errors", "newsletter.unsubscribe_page.invalid")));
			result.redirectTo(ListController.class).home(null);
			return;
		}
		result.include("mamuteMessages", asList(messageFactory.build("messages", "newsletter.unsubscribe_page.valid")));
		user.setSubscribed(false);
		result.redirectTo(ListController.class).home(null);
	}
	
	@CustomBrutauthRules(ModeratorOnlyRule.class)
	@Post
	public void toogleBanned(@Load User user) {
		if(user.isBanned()){
			user.undoBan();
		}else{
			user.ban();
			flaggable.turnAllInvisibleWith(user);
			users.clearSessionOf(user);
		}
		result.nothing();
	}

	private SanitizedText correctWebsite(SanitizedText website) {
		String text = website.getText();
		if(text.startsWith(HTTP))
			return website;
		return fromTrustedText(HTTP+text); 
	}
	
	private boolean redirectToRightSluggedName(User user, String sluggedName) {
		String correctSluggedName = user.getSluggedName();
		if (!correctSluggedName.equals(sluggedName)) {
			result.redirectTo(this).showProfile(user, correctSluggedName);
			return true;
		}
		return false;
	}
}

src/main/webapp/WEB-INF/jsp/userProfile/editProfile.jsp
<c:set var="title" value="${t['metas.edit_profile.title']}"/>
<c:set var="siteName" value="${t['site.name']}"/>

<c:set var="genericTitle" value="${t['metas.generic.title'].args(siteName)}"/>

<tags:header title="${genericTitle} - ${title}"/>

<div class="subheader">
	<tags:userProfileLink user="${user}" htmlClass="title page-title"/>
	<ul class="subheader-menu">
		<a href="${linkTo[UserProfileController].editProfile(user)}">${t['user_profile.edit']}</a>
	</ul>
</div>
<div class="image-and-information">
	<img class="profile-image" src="${user.getBigPhoto(env.get('gravatar.avatar.url'))}"/>
	<a href="${t['gravatar.url']}">${t['user_profile.edit.photo']}</a>
</div>

<form class="validated-form profile-edit-form" action="${linkTo[UserProfileController].editProfile(user)}" method="POST">
	<label for="name" class="form-label">${t['user_profile.edit.form.name.label']}</label>
	<input type="text" name="name" class="text-input required" minlength="4" maxlength="100" value="<c:out value="${user.name}" escapeXml="true"/>"/>
	
	<label for="email" class="form-label">${t['user_profile.edit.form.email.label']}</label>
	<input type="email" name="email" class="required text-input email" minlength="6" maxlength="100" value="<c:out value="${user.email}" escapeXml="true"/>"/>
	
	<label for="website" class="form-label">${t['user_profile.edit.form.website.label']}</label>
	<input type="text" name="website" class="text-input brutal-url" maxlength="200" value="<c:out value="${user.website}" escapeXml="true"/>"/>
	
	<label for="birthDate" class="form-label">${t['user_profile.edit.form.birth_date.label']}</label>
	<input type="text" name="birthDate" id="datepicker-age" class="text-input date" maxlength="10" value="<tags:jodaTime pattern="dd/MM/YYYY" time="${user.birthDate}"/>" placeholder="dd/mm/yyyy"/>
	
	<label for="location" class="form-label">${t['user_profile.edit.form.location.label']}</label>
	<input type="text" name="location" class="text-input" maxlength="100" value="<c:out value="${user.location}" escapeXml="true"/>"/>
	
	<label for="description" class="form-label">${t['user_profile.edit.form.about.label']}</label>
	<tags:markDown value="${user.about}" hintId="user-about-hint" minlength="6" maxlength="500" />

	<input type="checkbox" name="isSubscribed" class="text-input inline-box" maxlength="100" ${user.subscribedToNewsletter? 'checked':''} />
	<label for="isSubscribed" class="form-label inline-label">${t['user_profile.edit.form.subscribe.label']}</label>
	<input type="submit" class="post-submit big-submit submit" value="${t['user_profile.edit.form.submit']}"/>
	<tags:userProfileLink user="${user}" value="user_profile.edit.cancel"/>
</form>

src/main/webapp/WEB-INF/jsp/userProfile/reputationHistory.jsp
<c:set var="title" value="${t['metas.profile.title']}"/>
<c:set var="siteName" value="${t['site.name']}"/>

<c:set var="genericTitle" value="${t['metas.generic.title'].args(siteName)}"/>

<tags:header title="${genericTitle} - ${title}"/>

<tags:userProfileTab active="reputation">
<h2 class="title page-title"><span class="grey-text">${selectedUser.karma}</span> <span class="highlight">${t['user_profile.reputation']}</span></h2>
<section class="advanced-user-data user-data">
	<ul class="karma-history">
		<c:forEach var="historyItem" items="${reputationHistory}">
			<tags:reputationHistoryItem historyItem="${historyItem}">
				<span class="event-time"><tags:prettyTime time="${historyItem.date}"/></span>
			</tags:reputationHistoryItem>
		</c:forEach>
	</ul>
</section>
</tags:userProfileTab>

src/main/webapp/WEB-INF/jsp/userProfile/showProfile.jsp
<c:set var="title" value="${t['metas.profile.title']}"/>
<c:set var="siteName" value="${t['site.name']}"/>

<c:set var="genericTitle" value="${t['metas.generic.title'].args(siteName)}"/>

<tags:header title="${genericTitle} - ${title}"/>

<tags:userProfileTab  active="summary">
	<section class="advanced-user-data user-data">
		<div class="advanced-data-line-wrapper">
			<tags:userProfileAdvancedPostData pages="${questionsPageTotal}" count="${questionsCount}" i18n="questions" list="${questionsByVotes}" type="perguntas" orderOptions="true" withPagination="true"/>
			<tags:userProfileAdvancedPostData pages="${answersPageTotal}" count="${answersCount}" i18n="answers" list="${answersByVotes}" type="respostas" orderOptions="true" withPagination="true"/>
		</div>
		
		<div class="advanced-data-line-wrapper">
			<tags:userProfileAdvancedPostData pages="${watchedQuestionsPageTotal}" count="${watchedQuestionsCount}" list="${watchedQuestions}" i18n="watched_questions" type="acompanhadas" orderOptions="false" withPagination="true"/>
			
			<tags:userProfileAdvancedData i18n="karma_history" list="${reputationHistory}" count="${selectedUser.karma}" type="historico-reputacao" orderOptions="false" withPagination="false">
				<c:forEach var="historyItem" items="${reputationHistory}">
					<tags:reputationHistoryItem historyItem="${historyItem}"/>
				</c:forEach>
				<a class="view-more" href="${linkTo[UserProfileController].reputationHistory(selectedUser, selectedUser.sluggedName)}">${t['show_more']}</a>
			</tags:userProfileAdvancedData>
		</div>
		<div class="advanced-data-line-wrapper">
			<tags:userProfileAdvancedData i18n="tags" list="${userProfileMainTags}" type="tags" orderOptions="false" withPagination="false">
				<c:forEach var="tagUsage" items="${userProfileMainTags}">
					<li class="ellipsis advanced-data-line tag-line"><span class="counter tag-usage">${tagUsage.usage}</span> <tags:tag tag="${tagUsage.tag}"/></li>
				</c:forEach>
			</tags:userProfileAdvancedData>
		</div>
	</section>
</tags:userProfileTab>